In [64]:
import numpy as np
import math
import random

In [63]:
class Algoritma_genetika :

  jumlah_chromosome = 6
  gen = ["a", "b", "c", "d"]
  nilai_per_gen = {
    'min' : 0,
    'max' : 10
  }
  crossover_rate = 25/100
  mutasi_rate = 10/100
  total_generasi = 50
  next_gen = np.arange(4)
  stop = False
  def __init__(self):
    self.first_chromosome = np.random.randint(low=self.nilai_per_gen['min'], high=self.nilai_per_gen['max'], size=(self.jumlah_chromosome, len(self.gen)))
    print(self.first_chromosome)
    print("-------------------------------------------------------------")


  def evaluasi_chromosome(self, chromosome, generasi) :

    print("GENERASI ["+str(generasi)+"]")

    jumlah_chromosome = len(chromosome)
    j = np.arange(jumlah_chromosome)
    fitness = np.arange(jumlah_chromosome, dtype='f')

    for x in range(len(chromosome)):
      ev = abs((chromosome[x][0]+2*chromosome[x][1]+3*chromosome[x][2]+4*chromosome[x][3])-30)
      j[x] = ev

      fitn = 1/(ev+1)

      fitness[x] = fitn
      if(fitn == 1):
        self.stop = True
      print("CHROMOSOME {0} : {1}, FITNESS = {2}".format(x, np.array2string(chromosome[x], separator=','), fitn))
    print("FITNESS DONE")
    print(j)

    P = np.arange(jumlah_chromosome, dtype='f')

    total_fitness = fitness.sum()
    P = fitness / total_fitness
    print("Total Fitness : {}".format(str(total_fitness)))
    print("Rata-rata Fitness : {}".format(str(np.average(fitness))))
    print("Probabilitas : {}".format(np.array2string(P, separator=',')))
    print("Probabilitas Paling Tinggi : {}, Pada Chromosome".format(P[P.argmax()], str(P.argmax())))
    print("CHROMOSOME YANG MUNGKIN TERPILIH : {}".format(np.array2string(chromosome[P.argmax()], separator=',')),end="\n\n")

    self.next_gen = chromosome[P.argmax()]

    C = np.arange(jumlah_chromosome, dtype='f')
    total_x = 0
    for x in range(len(P)):
      total_x += P[x]
      C[x] = total_x

    R = np.random.sample(len(fitness))
    new_chromosome = np.arange(jumlah_chromosome*len(self.gen)).reshape(jumlah_chromosome, len(self.gen))

    for y in range(len(R)):
      for k in range(len(new_chromosome)):
        if(R[y] < C[0]):
          new_chromosome[y] = chromosome[0]
        elif((C[k-1] < R[y]) & (R[y] < C[k])):
          new_chromosome[y] = chromosome[k]

    R = np.random.sample(jumlah_chromosome)
    index_chromosome_parent = []
    for p in range(len(R)):
      if(R[p] < self.crossover_rate):
        index_chromosome_parent.append(p)

    posisi_CO = np.random.randint(low=1, high=len(self.gen), size=len(index_chromosome_parent))

    off_spring = np.arange(len(self.gen)*len(index_chromosome_parent)).reshape(len(index_chromosome_parent), len(self.gen))

    for i_parent in range(len(index_chromosome_parent)):
      index_chromosome_1 = index_chromosome_parent[i_parent]
      if(i_parent == len(index_chromosome_parent)-1):
        index_chromosome_2 = index_chromosome_parent[0]
      else:
        index_chromosome_2 = index_chromosome_parent[i_parent+1]

      cut_point = posisi_CO[i_parent]
      for p in range(len(new_chromosome[index_chromosome_1])):
        if(p >= posisi_CO[i_parent]):
          off_spring[i_parent][p] = new_chromosome[index_chromosome_2][p]
        else:
          off_spring[i_parent][p] = new_chromosome[index_chromosome_1][p]

    for x in range(len(off_spring)):
      new_chromosome[index_chromosome_parent[x]] = off_spring[x]

    total_gen = len(chromosome) * len(chromosome[0])
    jumlah_mutasi = self.mutasi_rate * total_gen
    jumlah_mutasi = int(jumlah_mutasi)

    random_i_mutasi = np.random.randint(low=0, high=total_gen, size=jumlah_mutasi)

    for x in range(len(random_i_mutasi)):
      index_mutasi = random_i_mutasi[x]
      banyak_chromosome = len(chromosome)
      banyak_gen = len(chromosome[0])
      random_value = random.randint(self.nilai_per_gen['min'], self.nilai_per_gen['max'])
      if(index_mutasi <= banyak_gen):
        new_chromosome[0][index_mutasi-1]
      else:
        posisi_y = index_mutasi/banyak_gen
        posisi_y = int(posisi_y)
        posisi_x = index_mutasi % banyak_gen
        new_chromosome[posisi_y][posisi_x] = random_value
    return new_chromosome

  def do_now(self):
    chromosome_current = self.first_chromosome
    for generasi in range(0, self.total_generasi):
      if(self.stop != True):
        chromosome_current = self.evaluasi_chromosome(chromosome_current, generasi)
    print("DONE")
    print("CHROMOSOME TERTINGGI ADALAH")
    print(self.next_gen)
          
run = Algoritma_genetika()
run.do_now()

[[3 6 6 3]
 [8 4 4 1]
 [3 0 0 6]
 [9 4 0 2]
 [2 7 8 4]
 [6 0 4 6]]
-------------------------------------------------------------
GENERASI [0]
CHROMOSOME 0 : [3,6,6,3], FITNESS = 0.0625
CHROMOSOME 1 : [8,4,4,1], FITNESS = 0.3333333333333333
CHROMOSOME 2 : [3,0,0,6], FITNESS = 0.25
CHROMOSOME 3 : [9,4,0,2], FITNESS = 0.16666666666666666
CHROMOSOME 4 : [2,7,8,4], FITNESS = 0.037037037037037035
CHROMOSOME 5 : [6,0,4,6], FITNESS = 0.07692307692307693
FITNESS DONE
[15  2  3  5 26 12]
Total Fitness : 0.92646015
Rata-rata Fitness : 0.15441002
Probabilitas : [0.06746108,0.3597924 ,0.26984432,0.1798962 ,0.03997694,0.08302902]
Probabilitas Paling Tinggi : 0.35979241132736206, Pada Chromosome
CHROMOSOME YANG MUNGKIN TERPILIH : [8,4,4,1]

GENERASI [1]
CHROMOSOME 0 : [8,4,0,2], FITNESS = 0.14285714285714285
CHROMOSOME 1 : [8,4,4,1], FITNESS = 0.3333333333333333
CHROMOSOME 2 : [9,4,0,2], FITNESS = 0.16666666666666666
CHROMOSOME 3 : [9,4,0,2], FITNESS = 0.16666666666666666
CHROMOSOME 4 : [9,4,4,1], FI